/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#822800",
        "on-secondary-fixed-variant": "#36485b",
        "surface-container-high": "#eae7e9",
        error: "#ba1a1a",
        primary: "#000000",
        "on-background": "#1b1b1d",
        "secondary-fixed-dim": "#b5c8df",
        "surface-tint": "#585e6f",
        "surface-bright": "#fcf8fa",
        "inverse-on-surface": "#f3f0f1",
        "primary-container": "#151b29",
        "primary-fixed": "#dde2f6",
        "on-error": "#ffffff",
        "inverse-surface": "#313031",
        "surface-container-lowest": "#ffffff",
        outline: "#76777d",
        "tertiary-fixed": "#ffdbcf",
        "surface-dim": "#dcd9da",
        "surface-container-highest": "#e5e2e3",
        "secondary-container": "#cfe2f9",
        tertiary: "#000000",
        "surface-container-low": "#f6f3f4",
        "inverse-primary": "#c1c6d9",
        "on-tertiary-fixed": "#380c00",
        "on-tertiary-container": "#d66034",
        "on-primary": "#ffffff",
        "surface-container": "#f0edee",
        "tertiary-container": "#380c00",
        "on-secondary-fixed": "#091d2e",
        "primary-fixed-dim": "#c1c6d9",
        "on-primary-container": "#7e8395",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#414756",
        "error-container": "#ffdad6",
        secondary: "#4e6073",
        surface: "#fcf8fa",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#ffb59c",
        "on-surface-variant": "#45464c",
        "on-primary-fixed": "#151b29",
        "on-secondary": "#ffffff",
        "surface-variant": "#e5e2e3",
        "on-secondary-container": "#526478",
        "secondary-fixed": "#d1e4fb",
        "outline-variant": "#c6c6cc",
        "on-surface": "#1b1b1d",
        background: "#fcf8fa",
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
